server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/notice
    username: root
    password: chrome2019
mybatis:
  configuration:
    map-underscore-to-camel-case: true